openapi: 3.0.0
info:
  title: "Project Tracker Web API"
  version: "1.0.0"
  contact:
    name: Eduardo Jaime
    email: ejaime@amazingdevs.ca
    url: https://amazingdevs.ca
servers:
  - url: http://localhost:3000/api
tags:
  - name: Georgian College
    description: This is our college name
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /projects:
    get:
      security:
        - basicAuth: []
      description: Returns a list of projects
      responses:
        '200':
          description: Unfiltered list of projects